# Generated by Django 2.1.7 on 2019-03-25 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_commented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.Comment'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='votes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postvotes', to='core.Vote'),
        ),
    ]
